export const SHOP_CATEGORIES = [
  { key: "fashion", label: "Fashion & Apparel" },
  { key: "electronics", label: "Electronics & Gadgets" },
  { key: "grocery", label: "Grocery & Essentials" },
  { key: "beauty", label: "Beauty & Personal Care" },
  { key: "books", label: "Books & Stationery" },
  { key: "home_kitchen", label: "Home & Kitchen" },
  { key: "furniture", label: "Furniture & Decor" },
  { key: "sports", label: "Sports & Fitness" },
  { key: "toys", label: "Toys & Games" },
  { key: "jewelry", label: "Jewelry & Accessories" },
  { key: "automotive", label: "Automotive Parts & Accessories" },
  { key: "health", label: "Health & Wellness" },
  { key: "pets", label: "Pet Supplies" },
  { key: "baby_kids", label: "Baby & Kids" },
  { key: "food_beverage", label: "Food & Beverages" },
  { key: "pharmacy", label: "Pharmacy & Medicine" },
  { key: "hardware", label: "Hardware & Tools" },
  { key: "art_crafts", label: "Art & Crafts" },
  { key: "music", label: "Music & Instruments" },
  { key: "digital", label: "Digital Products & Software" },
  { key: "mobile_accessories", label: "Mobile & Accessories" },
  { key: "computer_it", label: "Computer & IT Equipment" },
  { key: "cameras", label: "Cameras & Photography" },
  { key: "footwear", label: "Footwear" },
  { key: "bags_luggage", label: "Bags & Luggage" },
  { key: "watches", label: "Watches & Wearables" },
  { key: "outdoor", label: "Outdoor & Camping" },
  { key: "office_supplies", label: "Office Supplies" },
  { key: "plants_gardening", label: "Plants & Gardening" },
  { key: "cleaning", label: "Cleaning & Household" },
  { key: "travel", label: "Travel & Tourism" },
  { key: "gifts", label: "Gifts & Souvenirs" },
  { key: "services_repairs", label: "Services & Repairs" },
  { key: "handmade", label: "Handmade & Local Products" },
  { key: "automobile_sales", label: "Automobile Sales" },
  { key: "others", label: "Others" },
];

export const OPENING_HOURS_OPTIONS = [
  { key: "mon_fri_9_6", label: "Mon - Fri, 9 AM - 6 PM" },
  { key: "mon_sat_10_7", label: "Mon - Sat, 10 AM - 7 PM" },
  { key: "mon_sun_10_8", label: "Mon - Sun, 10 AM - 8 PM" },
  { key: "mon_fri_8_5", label: "Mon - Fri, 8 AM - 5 PM" },
  { key: "mon_sat_9_9", label: "Mon - Sat, 9 AM - 9 PM" },
  { key: "everyday_10_10", label: "Everyday, 10 AM - 10 PM" },
  { key: "weekends_only", label: "Weekends Only (Sat - Sun, 10 AM - 8 PM)" },
  { key: "mon_fri_evening", label: "Mon - Fri, 12 PM - 9 PM" },
  { key: "mon_fri_morning", label: "Mon - Fri, 7 AM - 2 PM" },
  { key: "everyday_24", label: "Open 24 Hours" },
  { key: "closed_sunday", label: "Mon - Sat, 9 AM - 6 PM (Closed Sunday)" },
  { key: "custom", label: "Custom Hours" },
];

export const BUSINESS_TYPES = [
  "Individual / Sole Proprietor",
  "Company / Corporation",
  "Partnership",
  "Limited Liability Company (LLC)",
  "Non-profit Organization",
];
